#!/bin/sh
set -eu

APP_DB_NAME="${APP_DB_NAME:?APP_DB_NAME is required}"
APP_DB_USER="${APP_DB_USER:?APP_DB_USER is required}"
APP_DB_PASSWORD_FILE="${APP_DB_PASSWORD_FILE:?APP_DB_PASSWORD_FILE is required}"
POSTGRES_PASSWORD_FILE="${POSTGRES_PASSWORD_FILE:?POSTGRES_PASSWORD_FILE is required}"
POSTGRES_USER="${POSTGRES_USER:-postgres}"

APP_DB_PASSWORD="$(cat "$APP_DB_PASSWORD_FILE")"
POSTGRES_PASSWORD="$(cat "$POSTGRES_PASSWORD_FILE")"

APP_DB_USER_ESCAPED="$(printf "%s" "$APP_DB_USER" | sed 's/"/""/g')"
APP_DB_NAME_ESCAPED="$(printf "%s" "$APP_DB_NAME" | sed 's/"/""/g')"
APP_DB_PASSWORD_ESCAPED="$(printf "%s" "$APP_DB_PASSWORD" | sed "s/'/''/g")"
APP_DB_USER_SQL_LITERAL_ESCAPED="$(printf "%s" "$APP_DB_USER" | sed "s/'/''/g")"

export PGPASSWORD="$POSTGRES_PASSWORD"

psql --username "$POSTGRES_USER" --dbname "$APP_DB_NAME" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = '$APP_DB_USER_SQL_LITERAL_ESCAPED'
  ) THEN
    EXECUTE 'CREATE ROLE "$APP_DB_USER_ESCAPED" LOGIN PASSWORD ''$APP_DB_PASSWORD_ESCAPED''';
  ELSE
    EXECUTE 'ALTER ROLE "$APP_DB_USER_ESCAPED" WITH LOGIN PASSWORD ''$APP_DB_PASSWORD_ESCAPED''';
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE "$APP_DB_NAME_ESCAPED" TO "$APP_DB_USER_ESCAPED";
GRANT USAGE ON SCHEMA public TO "$APP_DB_USER_ESCAPED";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "$APP_DB_USER_ESCAPED";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "$APP_DB_USER_ESCAPED";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$APP_DB_USER_ESCAPED";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "$APP_DB_USER_ESCAPED";
SQL
